Lesson 17
delosiliana/tutu pull request #3
Opened 2017-11-27 04:18 UTC by delosiliana

Сделала сортировку
Изменила вагоны на вложенные ресурсы
Добавила время прибытия и отправления
Сделала поиск
Добавила "купить билет" с выводом информации о билете

2017-11-27 10:06 UTC, iBublik requested changes

2017-11-27 10:06 UTC, iBublik commented on app/controllers/carriages_controller.rb
> +  def new
И зачем столько пробелов тут? Настрой редактор, чтоб он обрезал ненужные пробелы в конце строки

2017-11-27 10:06 UTC, iBublik commented on app/controllers/carriages_controller.rb
> +    @carriage = @train.carriages.new(carriage_params)
`train_id` по-прежнему передается в `carriage_params`

2017-11-27 10:06 UTC, iBublik commented on app/models/railway_station.rb
> +    @station_route ||= railway_stations_routes.where(route: route).first
Можно сократить до `railway_stations_routes.find_by(route: route)`

2017-11-27 10:06 UTC, iBublik commented on app/models/railway_station.rb
> +    station_route = station_route(route)
Зачем перекрывать метод локальной переменной с тем же именем? Вообще можно весь метод уместить в одну строку -  `station_route(route)&.update(position: position)`

2017-11-27 10:06 UTC, iBublik commented on app/models/railway_station.rb
> +    station_route(route).try(:position)
Рекомендую везде использовать `&` вместо `try`, т.к. последний позволяет вызывать на объекте методы, которых у него нет - `1.try(:hello_world)`. Это чревато ошибками (например, так можно не заметить опечатку в имени метода)

2017-11-27 10:06 UTC, iBublik commented on app/models/railway_station.rb
> +    station_route.update(arrival_time: arrival, departure_time: departure) if station_route
Замечания аналогичны методу `update_position`

2017-11-27 10:06 UTC, iBublik commented on app/models/railway_station.rb
> +    station_route(route).try(type_time).try(:strftime, '%H:%M')
Лушче `&` вместо `try`

2017-11-27 10:06 UTC, iBublik commented on app/models/ticket.rb
> +  validates :passport_series, presence: true
Незачем дублировать одинаковые описания валидаций, можно все разом записать - `validates : passenger_name, passenger_lastname, ..., presence: true`

2017-11-27 10:06 UTC, iBublik commented on db/migrate/20171127030058_add_column_to_tickets.rb
> +    add_column :tickets, :passenger_name, :string
Когда изменения вносятся в одну таблицу, намного проще использовать метод [`change_table`](http://devdocs.io/rails~5.1/activerecord/connectionadapters/schemastatements#method-i-change_table)

2017-11-27 10:06 UTC, iBublik commented on app/controllers/searches_controller.rb
> +  before_action :all_railway_station, only: [:show, :create]
Соблюдей консистентный нейминг - все before_action, где ты устанавливаешь инстанс переменные, имеют префикс `set`. Тут тоже лушче назвать `set_railway_stations`

2017-11-27 10:06 UTC, iBublik commented on app/controllers/searches_controller.rb
> +  def create
Есть ли смысл в отдельном экшене, если show не содержит логики вообще, а в create рендерится вьюха show? Можно в один экшен это все объединить

2017-11-27 10:06 UTC, iBublik commented on app/models/train.rb
> +  scope :station_on_route, -> (station) { joins(route: :railway_stations).where("railway_station_id = ?", station) }
Имя скоупа непонятное. При чем тут поезда и станции на маршруте? И параметр тоже непонятный - что там id или объект станции?

2017-11-27 10:06 UTC, iBublik commented on app/models/train.rb
> +  def self.search(start_station, finish_station)
Слишком общее имя метода

2017-11-27 10:06 UTC, iBublik commented on app/views/searches/show.html.erb
> +		<%= select_tag :start_station, options_from_collection_for_select(@stations, :id, :title) %>
Внезапно тут появились табы. Надо везде использовать пробелы, а то сейчас код лесенкой

2017-11-27 10:06 UTC, iBublik commented on app/views/searches/show.html.erb
> +<% if @error !="" %>
`if @error.present?`

2017-11-28 15:16 UTC, delosiliana commented on app/models/railway_station.rb
> +    station_route = station_route(route)
оно работает так, но рубокоп ругается.
unexpected token error
(Using Ruby 2.1 parser; configure using `TargetRubyVersion` parameter, under `AllCops`) (error:Lint/Syntax)

2017-11-29 03:33 UTC, iBublik approved these changes

2017-11-29 03:33 UTC, iBublik commented on app/controllers/searches_controller.rb
> +  def create
Я бы лучше отсавил `show`, но это уже дело вкуса :)

2017-11-29 03:33 UTC, iBublik commented on app/controllers/searches_controller.rb
> +    render :show
Вот видишь, подсознательно ты и сама считаешь, что это `show`, а не `create` :) так что стоит поменять экшн

2017-11-29 03:33 UTC, iBublik commented on app/models/ticket.rb
> +  validates :passport_number, :passport_series, presence: true
А эти поля зачем отдельно валидировать? Тут ведь все то же самое

2017-11-29 03:33 UTC, iBublik commented on app/models/train.rb
> +  scope :train_on_route, -> (station) { joins(route: :railway_stations).where("railway_station_id = ?", station) }
Замечания по неймингу актуальны

2017-11-29 03:33 UTC, iBublik commented on app/models/train.rb
> +  def self.search_train(start_station, finish_station)
`Train.search_train` - масло масляное. Лучше бы что-то типа `Train.search_by_stations`

2017-11-29 08:07 UTC, vkurennov approved these changes

2017-12-02 21:26 UTC, merged